### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by Ekleog** [Ekleog/todiff#22]
```
thread 'main' panicked at 'attempt to divide by zero', src/compute_changes.rs:282:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <&'a mut I as core::iter::iterator::Iterator>::next
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  11: todiff::stable_marriage::Matcher::compute_preference_list
  12: todiff::stable_marriage::stable_marriage
  13: todiff::compute_changes::compute_changeset
  14: todiff::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by Ekleog** [comment]
Apparently regression not present in the last release

**Comment by Ekleog** [comment]
(that said with the last release and the same (huge) diff I get nonsense, so…

**Comment by Ekleog** [comment]
OK that's reproducible with:
From:
```
foo
```
To:
```

```
(yes, an empty line, thus no subject, thus division by 0)

**Comment by Ekleog** [comment]
With https://github.com/Ekleog/todiff/pull/18/commits/9389f228bae5aff17f89a7a6a03e4d58040090d2 cherry-picked, it becomes (same reproducer):
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: todiff::compute_changes::compute_changeset
  14: todiff::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by Ekleog** [comment]
OK my bad, this second error is unrelated. So cherry-picking 9389f22 apparently fixes this one.

**Comment by Ekleog** [comment]
Reopening: missing a test case addition
