### ISSUE TITLE
Completed task without finish date

### ISSUE THREAD

**Issue by Ekleog** [Ekleog/todiff#23]
EDIT: This is basically https://github.com/Ekleog/todiff/blob/c11b62d0cc26d1a67211ca789ec16292aafd045e/src/compute_changes.rs#L160-161

Reproducer:
```
foo rec:1d
```
```
x foo
foo rec:1d
```

----

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: todiff::compute_changes::compute_changeset
  14: todiff::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
  20: __libc_start_main
  21: _start
```

Currently looking for a reasonably small reproducer

**Comment by Ekleog** [comment]
So, debug-based full stack trace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  10: todiff::compute_changes::recur_task
             at src/compute_changes.rs:161
  11: todiff::compute_changes::changes_between_rec
             at src/compute_changes.rs:252
  12: todiff::compute_changes::compute_changeset::{{closure}}::{{closure}}
             at src/compute_changes.rs:409
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  14: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:404
  15: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1347
  16: <core::iter::Chain<A, B> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:818
  17: <alloc::vec::Vec<T>>::extend_desugared
             at /checkout/src/liballoc/vec.rs:1900
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1797
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1792
  20: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1692
  21: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1372
  22: todiff::compute_changes::compute_changeset::{{closure}}
             at src/compute_changes.rs:410
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  24: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:404
  25: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1347
  26: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1823
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1806
  28: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1692
  29: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1372
  30: todiff::compute_changes::compute_changeset
             at src/compute_changes.rs:393
  31: todiff::main
             at src/main.rs:84
  32: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  33: std::panicking::try::do_call
  34: __rust_maybe_catch_panic
  35: std::rt::lang_start_internal
  36: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  37: main
  38: __libc_start_main
  39: _start
```
